<?php;
/** @var $block \Sportpat\HomeBanner\Block\Image */
?>
<span class="image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth()?>px;">
    <span class="image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100); ?>%;">
        <img class="image-photo lazyhome"
            <?= /* @escapeNotVerified */ $block->getCustomAttributes(); ?>
             src="<?= /* @escapeNotVerified */ $block->getImageUrl(); ?>"
             width="<?= /* @escapeNotVerified */ $block->getResizedImageWidth(); ?>"
             height="<?= /* @escapeNotVerified */ $block->getResizedImageHeight(); ?>"
             alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true); ?>"/></span>
</span>
