<?php
/** @var \Sportpat\HomeBanner\Block\Banner\ListBanner $block */
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>

<?php $banners = $block->getBanners();?>
<?php if ($banners->getSize()) : ?>


<ul class="home-promo-banners">


    <?php
    foreach($banners as $banner) {
        $width = 0;
        $height = 0;
        $subclass = "";
        switch($banner->getAttributeText('banner_size')) {
            case "rectangular-large":
                $width = 795;
                $height = 223;
                $subclass = "rl";
                break;
            case "square-small":
                $width = 397;
                $height = 306;
                $subclass = "ss";
                break;
            case "rectangular-small":
                $width = 397;
                $height = 223;
                $subclass = "rs";
            default:
                break;
        }


        ?>


        <li class="promo-banner <?php echo $subclass; ?>">
           <a href="<?php echo $banner->getBannerLink(); ?>" class="promo-banner-link" ><?= $block->getImage(
                $banner,
                'banner_view',
                ['width' => $width, 'height' => $height, 'type' => 'banner_image']
            )->toHtml(); ?></a>
        </li>

        <?php

    }
    ?>

</ul>

<?php endif; ?>


<!-- BRANDS -->

<h2 style="font-size:5.5rem;text-transform:uppercase;" class="mx-auto"><?php echo __("Our brands"); ?></h2>
<div class="home-brands-container">
    <ul class="home-brands row">
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=__empty__&amp;brand=509"><img src="/media/amasty/shopby/option_images/slider/509.jpg" alt="509" class="align-middle" height="85"></a></li>
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=THOR&brand=THOR"><img src="//imagessportpat.s3-accelerate.amazonaws.com/attribute/swatch/t/h/thor.jpg" alt="THOR" class="align-middle" height="85"></a></li>
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=CKX&amp;brand=CKX"><img src="/media/amasty/shopby/option_images/slider/CKX.jpg" alt="CKX" class="align-middle" height="85"></a></li>
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=FOX RACING&amp;brand=FOX RACING"><img src="/media/amasty/shopby/option_images/slider/Fox.jpg" alt="FOX RACING" class="align-middle" height="85"></a></li>
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=FXR RACING&amp;brand=FXR RACING"><img src="/media/amasty/shopby/option_images/slider/FXR.jpg" alt="FXR RACING" class="align-middle" height="85"></a></li>
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=G-MAX&amp;brand=G-MAX"><img src="/media/amasty/shopby/option_images/slider/Gmax-897843570.jpg" alt="G-MAX" class="align-middle" height="85"></a></li>
        <li class="brand-item col-sm-12 col-md-3 my-auto mx-auto"><a href="/<?php echo $storeManager->getStore()->getCode(); ?>/catalogsearch/result/?q=__empty__&amp;brand=TOBE"><img src="/media/amasty/shopby/option_images/slider/tobe-outerwear-coupons_1.png" alt="TOBE" class="align-middle" height="85"></a></li>
    </ul>
</div>

<?php
function getBrands() {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $conn = $resource->getConnection();
    $sql = "SELECT * FROM amasty_amshopby_option_setting WHERE filter_code = 'attr_brand' AND store_id=1 AND slider_image IS NOT NULL AND is_featured = 1 ORDER BY `value` LIMIT 8";
    $all = $conn->fetchAll($sql);
    return $all;
}
?>


<script type="text/javascript">
  /*  require([
        'jquery','lazyloader'
    ], function ($) {

      $(function($){
          $(".lazyhome").lazy({
              effect: "fadeIn",
              effectTime: 1000,
              threshold: 0
          });

      });


    });

   */
</script>
