<script>

    /* for code mirror */
    var SimpleGoogleShopping = {};

    var Utils = {
    sampleUrl : '<?php echo $block->getUrl("*/*/sample"); ?>',
    libraryUrl : '<?php echo $block->getUrl("*/*/library"); ?>',
    librarySampleUrl : '<?php echo $block->getUrl("*/*/librarysample"); ?>',
    categoriesUrl : '<?php echo $block->getUrl("*/*/categories"); ?>',
    sampleReportUrl : '<?php echo $block->getUrl("*/*/samplereport"); ?>'
}
</script>