<?php
/*
 * Copyright © 2015 Wyomind. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<!-- Preview popup template -->
<?php $content = $block->getContent(); ?>
<textarea id="preview"><?php echo $content; ?></textarea>
<style>
    .CodeMirror {
        height: 100%;
    }
</style>
<script>
    window.onload = function () {

        CodeMirror.fromTextArea(document.getElementById('preview'), {
            matchBrackets: true,
            mode: "application/x-httpd-php",
            indentUnit: 2,
            indentWithTabs: false,
            lineWrapping: false,
            lineNumbers: true,
            styleActiveLine: true,
            readOnly: true
        });

    };
</script>