<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID       = $storeManager->getStore()->getStoreId();
if($storeID == 1) {
?>

<footer class="page-footer">
    <div class="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                <div style="min-height: 100px; overflow: hidden;" class="shopperapproved_widget sa_rotate sa_count5 sa_horizontal sa_count5 sa_bgBlack sa_colorWhite sa_borderBlack sa_noborder sa_jMy sa_fill sa_showlinks sa_large sa_showdate "></div><script type="text/javascript">var sa_interval = 5000;function saLoadScript(src) { var js = window.document.createElement('script'); js.src = src; js.type = 'text/javascript'; document.getElementsByTagName("head")[0].appendChild(js); } if (typeof(shopper_first) == 'undefined') saLoadScript('//www.shopperapproved.com/widgets/testimonial/3.0/29777.js'); shopper_first = true; </script><div style="text-align:right;"><a class="sa_footer" href="https://www.shopperapproved.com/reviews/sportpat.com/" target="_blank" rel="nofollow"><img class="sa_widget_footer" style="border: 0;" alt="" src=https://www.shopperapproved.com/widgets/widgetfooter-darklogo.png></a></div>

                        <a href="https://www.shopperapproved.com/reviews/sportpat.com/" class="shopperlink shopper"><img
                                    src="//www.shopperapproved.com/newseals/29777/black-header-details.gif"
                                    style="border: 0" alt="Customer Reviews"
                                    oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by Shopper Approved \251 '+d.getFullYear()+'.'); return false;"></a>

                        <a href="https://www.facebook.com/Sportpat/" target="_blank" title="join sportpat on facebook" class="social-link"><i class="fab fa-2x fa-facebook"></i></a>
                        <a href="https://www.instagram.com/sportpat_/" target="_blank" title="join sportpat on instagram" class="social-link"><i class="fab fa-2x fa-instagram"></i></a>
                        <span class="social-link cloudflare">
</span>
                        <span class="social-link paypal"><img src="/media/paypal-payments.png" border="0" alt="PayPal Acceptance Mark"></a></span>

                    </div>


                </div>

            </div>
        </div>

        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="block">
                            <div class="block-title"><strong><span class="footer-title">Contact Information</span></strong></div>
                            <div class="block-content">
                                <ul class="contact-info" style="padding-top: 7px;">
                                    <li><p style="color: #fff !important; line-height:16px !important;"><b
                                                    style="color: #CC1212 !important;text-transform:uppercase;line-height:16px;font-weight:700;">Address</b><br>Sportpat<br>865
                                            av du Pont sud<br>
                                            Alma (Quebec) Canada<br>
                                            G8B 2V5</p></li>
                                    <li><p><b style="color: #CC1212;text-transform:uppercase;font-weight:700;">Phone</b><br><a
                                                    href="tel:+1-418-668-8118" style="color:#fff !important;">(418) 668-8118</a></p></li>
                                    <li><p><b style="color: #CC1212;text-transform:uppercase;font-weight:700;">Email</b><br><a
                                                    href="mailto:ventes@sportpat.com" style="color:#fff !important;">ventes@sportpat.com</a>
                                        </p></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="block-right">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="block">
                                                <div class="block-title"><strong><span class="footer-title">CUSTOMER SERVICE</span></strong>
                                                </div>
                                                <div class="block-content">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <ul class="links">
                                                                <li><a style="color: #fff !important;" title="Delivery"
                                                                       href="https://www.sportpat.com/en/delivery">Delivery</a>
                                                                </li>
                                                                <li><a style="color: #fff !important;" title="Returns"
                                                                       href="https://www.sportpat.com/en/returns">Returns</a>
                                                                </li>
                                                                <li><a style="color: #fff !important;" title="Warranty"
                                                                       href="https://www.sportpat.com/en/warranty">Warranty</a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <ul class="links">
                                                                <li><a style="color: #fff !important;"
                                                                       title="My Account"
                                                                       href="https://www.sportpat.com/en/customer/account">My
                                                                        Account</a></li>
                                                                <li><a style="color: #fff !important;" title="Login"
                                                                       href="https://www.sportpat.com/en/customer/account/login">Login</a>
                                                                </li>
                                                                <li><a style="color: #fff !important;"
                                                                       href="https://my.matterport.com/show/?m=DH96ymY1FUy"
                                                                       target="_blank"> 360° Virtual Tour </a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="block">
                                                <div class="block-title"><strong><span class="footer-title">Opening Hours</span></strong>
                                                </div>
                                                <div class="block-content">
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <ul class="features">
                                                                <li><a style="color: #fff !important;" href="#">Mon -
                                                                        Wed: 9am to 12pm - 1pm to 5pm</a></li>
                                                                <li><a style="color: #fff !important;" href="#">Thu -
                                                                        Fri: 9am to 12pm - 1pm to 5pm - 6pm to 8pm</a>
                                                                </li>
                                                                <li><a style="color: #fff !important;" href="#">Sat: 9am
                                                                        to 12pm</a></li>
                                                           <li><a style="color: #fff !important;" href="#">Sun: Closed</a></li>  </ul>
                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="block-bottom">
                                    <div class="row">
                                        <div class="col-md-5">
                                        </div>
                                        <div class="col-md-7">
                                            <div class="working" style="float: left;"></div>
                                            <div class="custom-block" style="float: right;"><img

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
      
</footer>
<?php }
if($storeID == 2) { ?>

    <footer class="page-footer">
        <div class="footer">
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">

                <div style="min-height: 100px; overflow: hidden;" class="shopperapproved_widget sa_rotate sa_count5 sa_horizontal sa_count5 sa_bgBlack sa_colorWhite sa_borderBlack sa_noborder sa_jMy sa_fill sa_showlinks sa_large sa_showdate "></div><script type="text/javascript">var sa_interval = 5000;function saLoadScript(src) { var js = window.document.createElement('script'); js.src = src; js.type = 'text/javascript'; document.getElementsByTagName("head")[0].appendChild(js); } if (typeof(shopper_first) == 'undefined') saLoadScript('//www.shopperapproved.com/widgets/testimonial/3.0/29777.js'); shopper_first = true; </script><div style="text-align:right;"><a class="sa_footer" href="https://www.shopperapproved.com/reviews/sportpat.com/" target="_blank" rel="nofollow"><img class="sa_widget_footer" style="border: 0;" alt="" src=https://www.shopperapproved.com/widgets/widgetfooter-darklogo.png></a></div>

                            <a href="https://www.shopperapproved.com/reviews/sportpat.com/" class="shopperlink shopper"><img
                                        src="//www.shopperapproved.com/newseals/29777/black-header-details.gif"
                                        style="border: 0" alt="Customer Reviews"
                                        oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by Shopper Approved \251 '+d.getFullYear()+'.'); return false;"></a>
  <a href="https://www.facebook.com/Sportpat/" target="_blank" title="join sportpat on facebook" class="social-link"><i class="fab fa-2x fa-facebook"></i></a>
                            <a href="https://www.instagram.com/sportpat_/" target="_blank" title="join sportpat on instagram" class="social-link"><i class="fab fa-2x fa-instagram"></i></a>
                            <span class="social-link cloudflare">
</span>
                            <span class="social-link paypal"><img src="/media/paypal-payments.png" border="0" alt="PayPal Acceptance Mark"></a></span>

                        </div>


                    </div>

                </div>
            </div>

            <div class="footer-middle">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="block">
                                <div class="block-title"><strong><span class="footer-title">NOUS CONTACTER</span></strong></div>
                                <div class="block-content">
                                    <ul class="contact-info" style="padding-top: 7px;">
                                        <li><p style="color: #fff !important; line-height:16px !important;"><b
                                                        style="color: #CC1212 !important;text-transform:uppercase;line-height:16px;font-weight:700;">Adresse</b><br>Sportpat<br>865
                                                av du Pont sud<br>
                                                Alma (Quebec) Canada<br>
                                                G8B 2V5</p></li>
                                        <li><p><b style="color: #CC1212;text-transform:uppercase;font-weight:700;">Tel.:</b><br><a
                                                        href="tel:+1-418-668-8118" style="color:#fff !important;">(418) 668-8118</a></p></li>
                                        <li><p><b style="color: #CC1212;text-transform:uppercase;font-weight:700;">Courriel</b><br><a
                                                        href="mailto:ventes@sportpat.com" style="color:#fff !important;">ventes@sportpat.com</a>
                                            </p></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-9">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="block-right">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="block">
                                                    <div class="block-title"><strong><span class="footer-title">SERVICE CLIENT</span></strong>
                                                    </div>
                                                    <div class="block-content">
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <ul class="links">
                                                                    <li><a style="color: #fff !important;" title="Livraison"
                                                                           href="https://www.sportpat.com/fr/livraison">Livraison</a>
                                                                    </li>
                                                                    <li><a style="color: #fff !important;" title="Retours"
                                                                           href="https://www.sportpat.com/fr/retours">Retours</a>
                                                                    </li>
                                                                    <li><a style="color: #fff !important;" title="Garantie"
                                                                           href="https://www.sportpat.com/fr/garantie">Garantie</a>
                                                                    </li>
                                                                </ul>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <ul class="links">
                                                                    <li><a style="color: #fff !important;"
                                                                           title="Mon Compte"
                                                                           href="https://www.sportpat.com/fr/customer/account">Mon Compte</a></li>
                                                                    <li><a style="color: #fff !important;" title="Connexion"
                                                                           href="https://www.sportpat.com/fr/customer/account/login">Connexion</a>
                                                                    </li>
                                                                    <li><a style="color: #fff !important;"
                                                                           href="https://my.matterport.com/show/?m=DH96ymY1FUy"
                                                                           target="_blank"> Tourn&eacute;e virtuelle 360°  </a></li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="block">
                                                    <div class="block-title"><strong><span class="footer-title">Heures d'ouverture</span></strong>
                                                    </div>
                                                    <div class="block-content">
                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <ul class="features">
                                                                    <li><a style="color: #fff !important;" href="#">Lun -
                                                                            Mer: 9:00 &agrave; midi - 13:00 &agrave; 17:00</a></li>
                                                                    <li><a style="color: #fff !important;" href="#">Jeu -
                                                                            Ven: 9:00 &agrave; midi - 13:00 &agrave; 17:00 - 18:00 &agrave; 20:00</a>
                                                                    </li>
                                                                    <li><a style="color: #fff !important;" href="#">Sam: 9:00
                                                                            &agrave; 12:00</a></li>
 <li><a style="color: #fff !important;" href="#">Dim:  Fermé</a></li>
 </ul>
                                                            </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="block-bottom">
                                        <div class="row">
                                            <div class="col-md-5">
                                            </div>
                                            <div class="col-md-7">
                                                <div class="working" style="float: left;"></div>
                                                <div class="custom-block" style="float: right;"><img

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    </footer>

<?php } ?>
<style>
    .footer-middle {
        background: #272723;
        padding-top:60px;
        padding-bottom:60px;
    }

    .footer-top {
        background: #111;
        padding-top: 60px;
        padding-bottom: 60px;
    }

    footer i {
        color:#fff;
    }

    .fa-facebook {
        content:"\f09a";
    }

    footer .shopper {
        display:inline-block;
        float:left;
        margin-top:5px;
    }

    footer .social-link {
        display:inline-block;
        float:right;
        margin-left:10px;
        margin-right:10px;
        margin-top:17px;
        max-height:48px;
    }

    footer .social-link.paypal {
        margin-top:-35px;
        padding:0;
    }


    footer .social-link.cloudflare {
        margin-top:7px;
        padding:0;
    }

    .footer-title {
        color:#fff;
        font-size:1.5rem;
        text-transform:uppercase;
        padding-left:40px;
        padding-bottom:20px;
    }

    .page-wrapper {
        width:100% !important;
    }

 @media screen and(max-width:991px) {

        .minicart-wrapper {
        position:absolute !important;
        top:0 !important;
        right:10px;}

     .page-product-configurable .page-wrapper {
         margin-top:120px !important;
     }


    }


    .amasty-label-container  img {
        height:auto !important;
	width:150px !important;
       /* max-height:60px !important;*/
        overflow:hidden !important;

    }

     .old-price.sly-old-price {
         display:block !important;
         color:#444 !important;
         text-decoration: line-through;
     }

    .product-options-bottom .price-box .price-container .price, .product-info-price .price-box .price-container .price {
        color:#E43635;
    }

    .product-options-bottom .price-box .price-container .old-price .price, .product-info-price .price-box .price-container .old-price .price {
        color:#444 !important;
    }

    .price-label {
        display:none !important;
    }

    .ais-HierarchicalMenu-item {
        display:none;
    }



    .ais-HierarchicalMenu-item.ais-HierarchicalMenu-item--selected.ais-HierarchicalMenu-item--parent, .ais-HierarchicalMenu-item.ais-HierarchicalMenu-item--selected.ais-HierarchicalMenu-item--parent  * {
        display:block !important;
    }

    .ais-HierarchicalMenu-item.ais-HierarchicalMenu-item--selected.ais-HierarchicalMenu-item--parent  .ais-HierarchicalMenu-count {
        display:none !important;
    }

    .catalogsearch-result-index .ais-HierarchicalMenu-item {
        display:block;
    }


</style>


<style>
    .wsmegamenu .submenu-icon > img:hover, .wsmegamenu a:hover .submenu-icon > img {
        border-color: red !important;
        text-decoration: none !important;
        transition: all ease-in 0.2s;
    }

    .wsmegamenu a {
        text-decoration: none !important;
        transition: all ease-in 0.2s;
        color:#444!important;
    }

    .wsmegamenu a:hover {
        text-decoration: none !important;
        transition: all ease-in 0.2s;
        color:red !important;
    }


    .wsmenu>.wsmenu-list>li>.wsmegamenu .title {
        text-shadow:none;

    }

    .wsmenu>.wsmenu-list>li>.wsmegamenu {
        color:#444;
        background: #fff;

        border-bottom:1px rgba(0,0,0,0.5);
        -webkit-box-shadow: 0px 10px 5px -6px rgba(0,0,0,0.32);
        -moz-box-shadow: 0px 10px 5px -6px rgba(0,0,0,0.32);
        box-shadow: 0px 10px 5px -6px rgba(0,0,0,0.32);
    }

    @media screen and (max-width:991px) {
        .overlapblackbg {
            width: calc(100% - 280px) !important;
        }
        .wsmenu > .wsmenu-list {
            width:280px !important;
        }
        .wsmenu > .wsmenu-list > li > .wsmenu-click > i::before {
            border-color:rgba(255,255,255,0.9) !important;
        }
        .wsmenu > .wsmenu-list > li > a {
            color:rgba(255,255,255,0.9) !important;
        }

        .page-product-configurable .page-wrapper {
            margin-top:120px !important;
        }

        .wsmobileheader {
            height:68px !important;
        }

        .wsactive .wsmobileheader {
            margin-left:280px !important;
        }

        .flaticon-snowmobile::before, .flaticon-motoneige::before {
            font-size:30px !important;
            margin:0 auto;
        }
        [class^="flaticon-"]::before, [class*=" flaticon-"]::before, [class^="flaticon-"]::after, [class*=" flaticon-"]::after {
            height:49px !important;
            font-size:30px !important;
        }
        .flaticon-famous::before {
            padding-left:15px !important;
        }
        .flaticon-dirt.bike::before, .flaticon-motocross::before {
            padding-top:5px !important;
        }

        select.mobile-lang-switcher {
            max-width:35px!important;float:right;background:#ffffff;position:absolute;top:10px;right:60px;z-index:4000;
            text-align:left;
            padding:0;
            color: rgba(0,0,0,0.7);
            border:none;
            font-weight:normal;
            font-size:14px !important;
            border-bottom:1px #991717 dotted !important;

        }

        li.authorization-link a {
            max-width:45px!important;float:left;background:#ffffff;position:absolute;top:15px;left:50px;z-index:4000;
            text-align:left;
            padding:0;
            padding-bottom:3px;
            color: rgba(0,0,0,0.7);
            border:none;
            font-weight:normal;
            font-size:14px !important;
            border-bottom:1px #991717 dotted !important;


        }

        li.authorization-link {
            list-style-type:none !important;
        }

        .wsmobileheader .smllogo {

            margin-top:15px !important;
            right:120px;
        }

        .searchautocomplete__active .block-search,

        .block-search #search_mini_form.form.minisearch.active {

            left:0 !important;
            right:0 !important;
            width:100vw !important;
            background:#ffffff;
            height:auto !important;
        }

        .mst-searchautocomplete__autocomplete._active {
            overflow:hidden !important;
            height:auto !important;
            display:block;
        }

    }

    @media (max-width:999px) {
        .wsmenu > .wsmenu-list > li > a
        i {
            margin-right:0px !important
        }
        .flaticon-casual:before,
        .flaticon-mode:before {
            content:"\f106";
            display:block;
            font-size:48px !important;
            margin-top:20px
        }
        .flaticon-famous:before {
            content:"\f107";
            display:block;
            padding-top:15px !important
        }
    }
    @media not all and (min-resolution:.001dpcm) {
        @media {
            [class^=flaticon-]:before,
            [class*=" flaticon-"]:before,
            [class^=flaticon-]:after,
            [class*=" flaticon-"]:after {
                font-family:Flaticon;
                font-size:34px;
                font-style:normal;
                margin-left:0;
                width:100px;
                height:59px;
                padding-top:0;
            }
            .flaticon-casual:before,
            .flaticon-mode:before {
                content:"\f106";
                display:block;
                font-size:48px !important
            }
        }
        @media (max-width:999px) {
            .flaticon-famous:before {
                content:"\f107";
                display:block;
                padding-top:15px;
            }
        }
    }

    @media all and (-webkit-min-device-pixel-ratio:0) and (min-resolution: .001dpcm) and (min-width:1280px) {
        .flaticon-dirt.bike:before, .flaticon-motocross:before, .flaticon-casual:before, .flaticon-mode:before,[class^=flaticon-]:before, [class*=" flaticon-"]:before, [class^=flaticon-]:after, [class*=" flaticon-"]:after {
            margin-top:-20px
        }
        .flaticon-snowmobile:before {
            margin-top:-40px
        }

    }

    @supports (-moz-appearance:meterbar) and (background-blend-mode:difference,normal) and (min-width:1280px) {
        .flaticon-dirt.bike:before, .flaticon-motocross:before, .flaticon-casual:before, .flaticon-mode:before,[class^=flaticon-]:before, [class*=" flaticon-"]:before, [class^=flaticon-]:after, [class*=" flaticon-"]:after {
            margin-top:0px
        }
        .flaticon-snowmobile:before {
            margin-top:-20px
        }
    }

    span.image-container span.image-wrapper img.image-photo.lazyhome {
        height:223px !important;
    }

    


</style>

