<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */

?>



<?= $block->getChildHtml() ?>



<style>
    .filter-title strong::before {
        font-family: "Font Awesome 5 Free";
        content: "\f1de";
        font-size: 27px;
        color: #818181;
        line-height: 30px;
        display: block;
        font-weight: 900;
        font-style: normal;
        font-variant: normal;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
    }


</style>

