<?php
/**
 * @var $this \Scommerce\GoogleUniversalAnalytics\Block\Adminhtml\Order\View
 */
?>
<?php
$helper = $this->getHelper();
$string = $this->getRefundData();
if (strlen($string)==0) return false;
$result = json_decode($string,true);
$storeId =  $result["storeId"];
?>

<script>
    //<![CDATA[
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '<?php echo $helper->getAccountId($storeId); ?>', '<?php echo $this->getMainDomain() ?>');
    ga('require', 'ec');
    <?php if (strlen($helper->isLinkAccountsEnabled($storeId))>0):?>
    ga('create','<?php echo $helper->getLinkedAccountId($storeId)?>',{'name':'<?php echo $helper->getLinkedAccountName($storeId)?>'});
    ga('<?php echo $helper->getLinkedAccountName($storeId)?>.require', 'ec');
    <?php endif;?>

    require(['jquery'], function($){
        $(window).load(function() {
            var refundOrder = <?php echo $string;?>
            //refundOrder = eval("(" + refundOrder + ")");
            if (refundOrder != undefined) {
                //console.log(refundOrder);
                //console.log(refundOrder.fullRefund);
                if (!(refundOrder.fullRefund)){
                    jQuery.each(refundOrder.products, function (index, product) {
                        //console.log(product);
                        ga('ec:addProduct', {
                            'id': product.id,
                            'quantity': product.qty
                        });
                    });
                }
                ga('ec:setAction', 'refund', {
                    'id': refundOrder.orderId
                });

                //console.log('Refunded - '+refundOrder.orderId);

                ga('send', 'event', 'Ecommerce', 'Refund', {'nonInteraction': 1});

                <?php if (strlen($helper->isLinkAccountsEnabled())>0):?>
                if (!(refundOrder.fullRefund)){
                    jQuery.each(refundOrder.products, function (index, product) {
                        ga('<?php echo $helper->getLinkedAccountName()?>.ec:addProduct', {
                            'id': product.id,
                            'quantity': product.qty
                        });
                    });
                }
                ga('<?php echo $helper->getLinkedAccountName()?>.ec:setAction', 'refund', {
                    'id': refundOrder.orderId
                });

                ga('<?php echo $helper->getLinkedAccountName()?>.send', 'event', 'Ecommerce', 'Refund', {'nonInteraction': 1});
                <?php endif;
				$this->unsRefundData();
				?>
               
            }
        });
    });

    //]]>
</script>