<?php
/**
 * @author Aitoc Team
 * @copyright Copyright (c) 2020 Aitoc (https://www.aitoc.com)
 * @package Aitoc_ReviewBooster
 */
?>
<?php
/**
 * Copyright © 2019 Aitoc. All rights reserved.
 */

// @codingStandardsIgnoreFile
use Aitoc\ReviewBooster\Api\Service\ConfigProviderInterface as ConfigHelperInterface;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\ObjectManagerInterface;
use Magento\Framework\View\TemplateEngine\Php as PhpTemplateEngine;
use Magento\Review\Block\Form as FormBlock;
use Magento\Review\Model\Rating;
use Magento\Review\Model\Rating\Option;
use Magento\Store\Model\StoreManagerInterface;

/**
 * @var FormBlock $block
 * @var PhpTemplateEngine $this
 */
?>
<?php

/** @var ObjectManagerInterface $objectManager */
$objectManager = ObjectManager::getInstance();
/** @var StoreManagerInterface $storeManager */
$storeManager = $objectManager->get(StoreManagerInterface::class);
$websiteId = $storeManager->getWebsite()->getId();

/** @var ConfigHelperInterface $configHelper */
$configHelper = $this->helper(ConfigHelperInterface::class);

$reviewRatingNames = $configHelper->getRatingNames($websiteId);

?>
<div class="block review-add">
    <div class="block-title"><strong><?php echo __('Aitoc_ReviewBooster:Write Your Own Review') ?></strong></div>
    <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form action="<?php echo $block->getAction() ?>" class="review-form" method="post" id="review-form" enctype="multipart/form-data" data-role="product-review-form" data-bind="scope: 'review-form'">
                <?php echo $block->getBlockHtml('formkey'); ?>
                <?php echo $block->getChildHtml('form_fields_before')?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('Aitoc_ReviewBooster:* Required Fields'); ?>">
                    <legend class="legend review-legend"><span><?php echo __("Aitoc_ReviewBooster:You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend><br />
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                        <span id="input-message-box"></span>
                        <fieldset class="field required review-field-ratings">
                            <legend class="label"><span><?php echo __('Aitoc_ReviewBooster:Your Rating') ?><span></legend><br/>
                            <div class="control">
                                <div class="nested" id="product-review-table">
                                    <?php
                                    /** @var Rating $rating */
                                    $ratingsCollection = $block->getRatings();

                                    foreach ($ratingsCollection as $rating): ?>
                                        <div class="field choice review-field-rating">
                                            <?php if(count($ratingsCollection) > 1): ?>
                                                <label class="label" id="<?php echo $block->escapeHtml($rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($rating->getRatingCode()) ?></span></label>
                                            <?php else: ?>
                                                <label class="label" id="<?php echo $block->escapeHtml($rating->getRatingCode()) ?>_rating_label"><span></span></label>
                                            <?php endif; ?>
                                            <div class="control review-control-vote">
                                                <?php
                                                /** @var Option $options */
                                                $options = $rating->getOptions();?>
                                                <?php $iterator = 1; foreach ($options as $option): ?>
                                                    <input
                                                            type="radio"
                                                            name="ratings[<?php echo $rating->getId() ?>]"
                                                            id="<?php echo $block->escapeHtml($rating->getRatingCode()) ?>_<?php echo $option->getValue() ?>"
                                                            value="<?php echo $option->getId() ?>"
                                                            class="radio"
                                                            data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                                            aria-labelledby="<?php echo $block->escapeHtml($rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($rating->getRatingCode()) ?>_<?php echo $option->getValue() ?>_label" />
                                                    <label
                                                            class="rating-<?php echo $iterator; ?>"
                                                            for="<?php echo $block->escapeHtml($rating->getRatingCode()) ?>_<?php echo $option->getValue() ?>"
                                                            title="<?php echo __('Aitoc_ReviewBooster:' . $reviewRatingNames[$iterator]) ?>"
                                                            id="<?php echo $block->escapeHtml($rating->getRatingCode()) ?>_<?php echo $rating->getId() ?>_<?php echo $option->getValue() ?>_label">
                                                        <span><?php echo __('Aitoc_ReviewBooster:' . $reviewRatingNames[$iterator]) ?></span>
                                                    </label>
                                                    <?php $iterator++; ?>
                                                <?php endforeach; ?>
                                                <span id="rating-name-<?php echo $rating->getId() ?>" class="rating-name"></span>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                            </div>
                        </fieldset>
                    <?php endif ?>
                    <div class="field review-field-nickname">
                        <label for="nickname_field" class="label"><span><?php echo __('Aitoc_ReviewBooster:Nickname') ?></span></label>
                        <div class="control">
                            <input type="text" name="nickname" id="nickname_field" class="input-text" data-bind="value: nickname()" />
                        </div>
                    </div>
                    <div class="field review-field-summary required">
                        <label for="summary_field" class="label"><span><?php echo __('Aitoc_ReviewBooster:Summary') ?></span></label>
                        <div class="control">
                            <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label"><span><?php echo __('Aitoc_ReviewBooster:Review') ?></span></label>
                        <div class="control">
                            <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        </div>
                    </div>
                    <div class="field review-field-advantages">
                        <label for="advantages_field" class="label"><span><?php echo __('Aitoc_ReviewBooster:What I like about this product') ?></span></label>
                        <div class="control">
                            <input type="text" name="product_advantages" id="advantages_field" class="input-text" data-validate="{required:false}" data-bind="value: review().advantages" />
                        </div>
                    </div>
                    <div class="field review-field-disadvantages">
                        <label for="disadvantages_field" class="label"><span><?php echo __('Aitoc_ReviewBooster:What I don\'t like about this product') ?></span></label>
                        <div class="control">
                            <input type="text" name="product_disadvantages" id="disadvantages_field" class="input-text" data-validate="{required:false}" data-bind="value: review().disadvantages" />
                        </div>
                    </div>
                    <?php if ($configHelper->isUploadImageEnabled($websiteId)): ?>
                        <div class="field review-field-image">
                            <div class="upper-control">
                                <label for="image_field" class="label"><span><?php echo __('Aitoc_ReviewBooster:Upload Image') ?></span></label>
                                <span> <a class="add_button general_button" id="add" onclick="addField()"></a></span>
                            </div>
                            <div class="control" id="control">
                                <div id="row_0" data-repeat-index="0" class="row_image">
                                    <input type="file" name="image_0" id="image_field" class="input-text"
                                        data-validate="{required:false}" data-bind="value: review().image"/>
                                <a class="remove_button general_button" onclick="deleteField(this)"></a>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>
                </fieldset>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary"><span><?php echo __('Aitoc_ReviewBooster:Submit Review') ?></span></button>
                    </div>
                </div>
            </form>
            <script type="text/javascript">
                function addField() {
                    var controlElement = document.getElementById('control');
                    var fieldIncrement = controlElement.childElementCount;

                    var div = document.createElement("div");
                    div.id = "row_" + fieldIncrement;
                    div.classList.add("row_image");
                    div.setAttribute("data-repeat-index", fieldIncrement);

                    var input = document.createElement("input");
                    input.type = "file";
                    input.name = "image_" + fieldIncrement;
                    var deleteButton = document.createElement("a");
                    deleteButton.classList.add("remove_button", "general_button");
                    deleteButton.setAttribute('onclick', 'deleteField(this)');

                    controlElement.appendChild(div);
                    div.appendChild(input);
                    div.appendChild(deleteButton);
                }

                function deleteField(button) {

                    if (button.parentElement.getAttribute('data-repeat-index') == 0) {
                        document.getElementById("image_field").value = "";
                    } else {
                        button.parentElement.remove();
                    }
                }
            </script>
            <script>
                require([
                    "jquery",
                    "mage/mage"
                ], function($){
                    $('#review-form').mage('validation', {
                        errorPlacement: function (error, element) {
                            if (element.parents('#product-review-table').length) {
                                $('#product-review-table').siblings(this.errorElement + '.' + this.errorClass).remove();
                                $('#product-review-table').after(error);
                            } else {
                                element.after(error);
                            }
                        }
                    });
                });
            </script>
            <script>
                require([
                    "jquery"
                ], function($){
                    $(function () {
                        $('body')
                            .on('mouseover', '[class^="rating-"]', function (event) {
                                var ratingId = this.id.split('_');
                                $('#rating-name-' + ratingId[1]).text(this.title);
                            })
                            .on('mouseout', '[class^="rating-"]', function (event) {
                                var ratingId = this.id.split('_');
                                if (!$('input[id^=' + ratingId[0] + '_]:checked').val()) {
                                    $('#rating-name-' + ratingId[1]).text('');
                                } else {
                                    var checkedId = $('input[id^=' + ratingId[0] + '_]:checked').attr('id').split('_');
                                    var ratingName = $('#' + checkedId[0] + '_' + ratingId[1] + '_' + checkedId[1] + '_label').attr('title');
                                    $('#rating-name-' + ratingId[1]).text(ratingName);
                                }
                            });
                    });
                });
            </script>
            <script type="text/x-magento-init">
            {
                "[data-role=product-review-form]": {
                    "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
                }
            }
            </script>
        <?php else: ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?php echo __('Aitoc_ReviewBooster:Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
