<?php;
/** @var $block \Sportpat\Tabcontent\Block\Image */
?>
<img class="photo image"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes(); ?>
     src="<?= /* @escapeNotVerified */ $block->getImageUrl(); ?>"
     width="<?= /* @escapeNotVerified */ $block->getWidth(); ?>"
     height="<?= /* @escapeNotVerified */ $block->getHeight(); ?>"
     alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true); ?>" />
